name: Validate commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check editorconfig
      run: docker run --rm --volume=$PWD:/check mstruebing/editorconfig-checker
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Test
      run: ./gradlew test
